### ISSUE TITLE
Does not work if lsp mode is active.

### ISSUE THREAD

**Issue by gamedolphin** [weijiangan/flycheck-golangci-lint#8]
Great package! But unfortunately, it stops working if lsp mode is active, which provides its own flycheck errors but not the same as golangci-lint.

**Comment by sagarc03** [comment]
@gamedolphin you might find [this](https://github.com/hlissner/doom-emacs/issues/1530#issuecomment-725588733) answer useful

**Comment by Gleek** [comment]
For non- doom-emacs usage discussion [here](https://github.com/flycheck/flycheck/issues/1762) might be more useful.
I've the following snippet, inspired from the discussion in the link above, to make it work.
```elisp
(defvar-local flycheck-local-checkers nil)
  (defun +flycheck-checker-get(fn checker property)
    (or (alist-get property (alist-get checker flycheck-local-checkers))
        (funcall fn checker property)))
  (advice-add 'flycheck-checker-get :around '+flycheck-checker-get)


(add-hook 'go-mode-hook (lambda()
                            (flycheck-golangci-lint-setup)
                            (setq flycheck-local-checkers '((lsp . ((next-checkers . (golangci-lint))))))))

**Comment by gamedolphin** [comment]
> For non- doom-emacs usage discussion [here](https://github.com/flycheck/flycheck/issues/1762) might be more useful.
> I've the following snippet, inspired from the discussion in the link above, to make it work.
> 
> ```emacs-lisp
> (defvar-local flycheck-local-checkers nil)
>   (defun +flycheck-checker-get(fn checker property)
>     (or (alist-get property (alist-get checker flycheck-local-checkers))
>         (funcall fn checker property)))
>   (advice-add 'flycheck-checker-get :around '+flycheck-checker-get)
> 
> 
> (add-hook 'go-mode-hook (lambda()
>                             (flycheck-golangci-lint-setup)
>                             (setq flycheck-local-checkers '((lsp . ((next-checkers . (golangci-lint))))))))
> ```

This actually works! Thanks!

**Comment by dsh2dsh** [comment]
I think better use
```lisp
'((lsp . ((next-checkers . ((warning . golangci-lint))))))
```
instead of
```lisp
'((lsp . ((next-checkers . (golangci-lint)))))
```

because with `warning` we are configuring flycheck to run `golangci-lint` after lsp will not find any syntax errors. Without it flycheck will run `golangci-lint` in any case and it'll return weird list of errors. So my current solution for using lsp + flycheck + golangci-lint is:
```lisp
(use-package flycheck
  :defer t
  :hook (go-mode . flycheck-mode)
  :config
  (defvar-local flycheck-local-checkers nil)
  (defun +flycheck-checker-get(fn checker property)
    (or (alist-get property (alist-get checker flycheck-local-checkers))
        (funcall fn checker property)))
  (advice-add 'flycheck-checker-get :around '+flycheck-checker-get))

(use-package go-mode
  :defer t
  :hook (go-mode . lsp-deferred)
  :config
  (defun lsp-go-install-save-hooks ()
    (add-hook 'before-save-hook #'lsp-format-buffer t t)
    (add-hook 'before-save-hook #'lsp-organize-imports t t))
  (add-hook 'go-mode-hook #'lsp-go-install-save-hooks)

  (flycheck-define-checker golangci-lint
    "A Go syntax checker using golangci-lint that's 5x faster than gometalinter

See URL `https://github.com/golangci/golangci-lint'."
  :command ("golangci-lint" "run" "--out-format=checkstyle" "--deadline=1m" ".")
  :error-parser flycheck-parse-checkstyle
  :error-patterns
  ((error line-start (file-name) ":" line ":" column ": " (message) line-end)
   (error line-start (file-name) ":" line ":" (message) line-end))
  :modes go-mode
  :predicate flycheck-buffer-saved-p)
  (add-to-list 'flycheck-checkers 'golangci-lint)

  (defun dsh/flycheck-golangci-lint-setup ()
    (setq flycheck-local-checkers
          '((lsp . ((next-checkers . ((warning . golangci-lint))))))))
  (add-hook 'go-mode-hook #'dsh/flycheck-golangci-lint-setup))
```

**Comment by Gleek** [comment]
> I think better use
`'((lsp . ((next-checkers . ((warning . golangci-lint))))))`

This won't work as the linter specifically checks for the severity [after the switch to checkstyle format](https://github.com/weijiangan/flycheck-golangci-lint/pull/10).

To force them as warnings I had to override the error parser and convert all errors to warnings.

The following is the code for it:
```elisp
(defun +flycheck-parse-checkstyle-warnings-only (output checker buffer)
  "Parse Checkstyle errors from OUTPUT and return only warnings.

This function converts all errors to warnings for the specified CHECKER (golangci-lint).
See `flycheck-parse-checkstyle' for more details on the parameters"
  (let ((original-errors (flycheck-parse-checkstyle output checker buffer)))
    (mapcar (lambda (error)
              (when (eq (flycheck-error-level error) 'error)
                (setf (flycheck-error-level error) 'warning))
              error)
            original-errors)))
(setf (flycheck-checker-get 'golangci-lint 'error-parser)
      #'+flycheck-parse-checkstyle-warnings-only)

```

**Comment by oodzchen** [comment]
This still happens to me on doom-emacs, here is my config

```
(use-package! flycheck-golangci-lint
  :init (setq flycheck-golangci-lint-fast t)
  :hook (go-mode . flycheck-golangci-lint-setup))
```

And after running `flycheck-verify-setup` , it shows
```
Checkers that could run if selected:

  golangci-lint  select
    - may enable: yes
    - executable: Found at /home/kn/go/bin/golangci-lint

...
```

But there's no error message in the flycheck buffer, while if I run `golangci-lint run` in terminal, many errors show up.

The doom-emacs discussion link above has been removed, I can't find a solution for this? do I need manually configure the checkers chain?
